runtime: python39

instance_class: F1

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /styles.css
  static_files: styles.css
  upload: styles.css

- url: /app.js
  static_files: app.js
  upload: app.js

- url: /(.*)
  static_files: \1
  upload: (.*)
