name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GAE
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to App Engine
      uses: google-github-actions/deploy-appengine@v1
      with:
        deliverables: 'app.yaml'
        promote: true
